//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_2021
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikl
    {
        public int ID_Artikl { get; set; }
        public string Naziv { get; set; }
        public double Cijena { get; set; }
        public Nullable<int> Normativ_ID { get; set; }
        public int Kategorija_ID { get; set; }
        public Nullable<int> Kafic_ID { get; set; }
    }
}
