//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_2021_Kafic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artikl()
        {
            this.Stavka_racuna = new HashSet<Stavka_racuna>();
        }
    
        public int ID_Artikl { get; set; }
        public string Naziv { get; set; }
        public double Cijena { get; set; }
        public Nullable<int> Normativ_ID { get; set; }
        public int Kategorija_ID { get; set; }
        public Nullable<int> Kafic_ID { get; set; }
    
        public virtual Kategorija Kategorija { get; set; }
        public virtual Normativ Normativ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_racuna> Stavka_racuna { get; set; }
    }
}
