//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_2021_Kafic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Namirnica
    {
        public int ID_Namirnica { get; set; }
        public string Naziv_Namirnice { get; set; }
        public double Kolicina { get; set; }
        public Nullable<int> Mjera_ID { get; set; }
        public Nullable<int> Sastojak_ID { get; set; }
        public int Skladiste_ID { get; set; }
        public Nullable<int> Kafic_ID { get; set; }
    
        public virtual Mjera Mjera { get; set; }
        public virtual Sastojak Sastojak { get; set; }
        public virtual Skladiste Skladiste { get; set; }
    }
}
