//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_2021_Kafic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Namirnica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Namirnica()
        {
            this.Stavka_normativa = new HashSet<Stavka_normativa>();
        }
    
        public int ID_Namirnica { get; set; }
        public string Naziv_Namirnice { get; set; }
        public Nullable<double> Kolicina_na_skladistu { get; set; }
        public string Mjera { get; set; }
        public int Skladiste_ID { get; set; }
        public Nullable<int> Kafic_ID { get; set; }
    
        public virtual Skladiste Skladiste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka_normativa> Stavka_normativa { get; set; }
    }
}
