//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_2021_Kafic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pod_Stavka
    {
        public int ID_Podstavka { get; set; }
        public int Mjera_ID { get; set; }
        public int Sastojak_ID { get; set; }
        public double Količina { get; set; }
        public int Stavka_normativa_ID { get; set; }
    
        public virtual Mjera Mjera { get; set; }
        public virtual Sastojak Sastojak { get; set; }
        public virtual Stavka_normativa Stavka_normativa { get; set; }
    }
}
