//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_2021_Kafic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavka_normativa
    {
        public int ID_Stavka_normativa { get; set; }
        public int Namirnica_ID { get; set; }
        public int Normativ_ID { get; set; }
        public double Kolicina { get; set; }
    
        public virtual Namirnica Namirnica { get; set; }
        public virtual Normativ Normativ { get; set; }
    }
}
