//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_2021_Kafic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavka_racuna
    {
        public int Racun_ID { get; set; }
        public int Artikl_ID { get; set; }
        public int Količina { get; set; }
        public double Cijena { get; set; }
    
        public virtual Artikl Artikl { get; set; }
        public virtual Racun Racun { get; set; }
    }
}
